{% set name = "pybase64" %}
{% set version = "1.4.0" %}
{% set sha256 = "714f021c3eaa287c1097ced68f2df4c5b2ecd2504551c2e71c843f54365aca03" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  # set CIBUILDWHEEL to throw errors if the C extension fails to build
  script_env:
    - CIBUILDWHEEL=1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pybase64=pybase64.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pybase64

about:
  home: https://github.com/mayeut/pybase64/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast Base64 encoding/decoding in Python
  doc_url: https://github.com/mayeut/pybase64/
  dev_url: https://github.com/mayeut/pybase64/

extra:
  recipe-maintainers:
    - njzjz
