{% set name = "pybase64" %}
{% set version = "1.2.0" %}
{% set sha256 = "9e310fcf5cfa2cbf7d1d7eb503b6066bec785216bcd1d8c0a736f59d5ec21b0b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pybase64=pybase64.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pybase64

about:
  home: https://github.com/mayeut/pybase64/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast Base64 encoding/decoding in Python
  doc_url: https://github.com/mayeut/pybase64/
  dev_url: https://github.com/mayeut/pybase64/

extra:
  recipe-maintainers:
    - njzjz
